# Generated by Django 4.2.3 on 2023-07-29 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price_per_day', models.IntegerField()),
                ('price_per_person', models.IntegerField()),
                ('max_num_people', models.IntegerField()),
                ('num_of_beds', models.IntegerField()),
                ('num_of_bedrooms', models.IntegerField()),
                ('num_of_bathrooms', models.IntegerField()),
                ('room_type', models.CharField(choices=[('p', 'Private'), ('s', 'Shared'), ('h', 'House')], max_length=1)),
                ('area', models.IntegerField()),
                ('living_room', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('air_condition', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('stove', models.BooleanField(default=False)),
                ('television', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('review_text', models.TextField()),
                ('date', models.DateField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.room')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.room')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('previous_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.message')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airbnb.room')),
            ],
        ),
    ]
