# Generated by Django 4.2.3 on 2023-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_review_user_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
