# Generated by Django 4.2.3 on 2023-07-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
    ]
