# Generated by Django 4.2.3 on 2023-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('h', 'host'), ('r', 'regular'), ('m', 'moderator')], default='r', max_length=1),
        ),
    ]
