# Generated by Django 4.2.3 on 2023-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('m', 'moderator'), ('r', 'regular'), ('h', 'host')], default='r', max_length=1),
        ),
    ]
